
apiVersion: v1
data:
  password: WjRyMHhjMGU=
  username: ZGVtb0ByZWRpcy5jb20=
kind: Secret
metadata:
  name: redis-enterprise-rerc-cacentral
  namespace: redis
type: Opaque

---

apiVersion: v1
data:
  password: V0Q0MjJiVWc=
  username: ZGVtb0ByZWRpcy5jb20=
kind: Secret
metadata:
  name: redis-enterprise-rerc-useast
  namespace: redis
type: Opaque