apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseRemoteCluster
metadata:
  name: rerc-cacentral
  namespace: redis
spec:
  recName: demo-clustera
  recNamespace: redis
  apiFqdnUrl: rerc-cacentral.redis
  dbFqdnSuffix: -db-cacentral.redis
  secretName: redis-enterprise-rerc-cacentral