apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
availabilityZones: [${CLUSTER_AZS}]

metadata:
  name: cc-eks-mcm2
  region: ${CLUSTER_REGION}
  version: "${EKS_VERSION}"

iam:
  withOIDC: true

addonsConfig:
  disableDefaultAddons: true
  autoApplyPodIdentityAssociations: true
addons:
  - name: kube-proxy
  - name: coredns
  - name: aws-ebs-csi-driver
  - name: eks-pod-identity-agent

kubernetesNetworkConfig:
  serviceIPv4CIDR: "172.21.0.0/16"  

vpc:
  cidr: 10.10.0.0/24


nodeGroups: []