apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
availabilityZones:
  - us-east-1c
  - us-east-1d

metadata:
  name: cc-eks-mcm2
  region: us-east-1
  version: "1.26"

kubernetesNetworkConfig:
  serviceIPv4CIDR: "172.21.0.0/16"  

vpc:
  cidr: 10.10.0.0/24


nodeGroups: []