apiVersion: v1
kind: Service
metadata:
  name: nginx-federated
  annotations:
    federation.tigera.io/serviceSelector: federation == "yes"
spec:
  ports:
    - port: 80
      protocol: TCP
  type: ClusterIP