apiVersion: v1
kind: Service
metadata:
  name: rerc-useast
  namespace: redis
  annotations:
    federation.tigera.io/serviceSelector: redis-enterprise-api-region == "useast"
spec:
  ports:
  - name: sentinel
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: api
    port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP